##
# docker-compose.gcp.yml
#
# Usage:
#   export DOCKER_IMAGE_TAG=$(git rev-parse --short HEAD)
#   docker-compose -f docker-compose.yml -f docker-compose.gcp.yml
##
version: '3'

services:
 client:
   image: gcr.io/development-171220/client-app:${DOCKER_IMAGE_TAG:-latest}
 server:
   image: gcr.io/development-171220/server-app:${DOCKER_IMAGE_TAG:-latest}